# This file was generated by Gemini

CC = gcc
CFLAGS = -Wall -Wextra -Wpedantic -std=c99 -Iinclude -D_POSIX_C_SOURCE=200112L

SRC_DIR = src
APPS_DIR = apps
BIN_DIR = bin

# Lib files (compiled once in .o)
LIB_SRCS = $(wildcard $(SRC_DIR)/*.c)
LIB_OBJS = $(LIB_SRCS:.c=.o)

# All apps in apps/
APP_SRCS = $(wildcard $(APPS_DIR)/*.c)
# Transforming apps/name.c -> bin/name
TARGETS  = $(patsubst $(APPS_DIR)/%.c, $(BIN_DIR)/%, $(APP_SRCS))

.PHONY: all clean

# Main goal — collect all binaries
all: $(TARGETS)

# Rule for creating bin/
$(BIN_DIR):
	mkdir -p $(BIN_DIR)

# Compiling .c files from src/ in .o
$(SRC_DIR)/%.o: $(SRC_DIR)/%.c
	$(CC) $(CFLAGS) -c $< -o $@

# Linking every app with lib .o files
$(BIN_DIR)/%: $(APPS_DIR)/%.c $(LIB_OBJS) | $(BIN_DIR)
	$(CC) $(CFLAGS) $< $(LIB_OBJS) -o $@

# Clearing all build artefacts
clean:
	rm -rf $(BIN_DIR) $(SRC_DIR)/*.o